### ISSUE TITLE
Ignoring certain properties at scripting

### ISSUE THREAD

**Issue by peterbud** [action-bi-toolkit/pbi-tools#51]
I have been using pbi-tools for a few days now, and I find it super good - a real game changer IMHO.

What I have seen is that I get a lot of "noise" changes when I script the PBIX model, and I was thinking what would be the impact of suppressing scripting certain properties.

Example: 
* `lastModified `property: every time I save the file (like refresh data), this property will change although there is no structural change in the PBIX file
* I have seen a bunch of properties (I guess PBI internal stuff), like PBI_ChangedProperties. Like changing a field from visible to invisible is not just adding `isHidden: true` (which is OK and expected), but also     
```
   {
      "name": "PBI_ChangedProperties",
      "value": "[\"IsHidden\"]"
    } 

```
So are these properties really needed to compile a new PBIX from the scripted model, or would it make sense NOT to script them?

**Comment by mthierba** [comment]
Possibly covered by #19 

Here's a design proposal:
- Make this behavior configurable instead of prescribing it.
- Extend the existing _Model_ settings held in `.pbixproj.json` (https://github.com/action-bi-toolkit/pbi-tools/blob/1.0.0-beta.6/src/PBI-Tools/ProjectSystem/ModelSettings.cs)
- Add an optional property `excludeAttributes`/`attributes` to specify include/exclude rules for TMSL attributes. Support wildcards.

## Example `.pbixproj.json` No 1 (Simple)
```
{
  "version": "0.9",
  "created": "2021-10-17T22:21:52.2717082+01:00",
  "lastModified": "2021-10-17T22:21:55.2160879+01:00",
  "settings": {
    "model": {
      "serializationMode": "Default",
      "ignoreProperties": [],
      "excludeAttributes": [
        "PBI_*"
      ]
    }
  }
}
```

## Example `.pbixproj.json` No 2 (Complex)
```
{
  "version": "0.9",
  "created": "2021-10-17T22:21:52.2717082+01:00",
  "lastModified": "2021-10-17T22:21:55.2160879+01:00",
  "settings": {
    "model": {
      "serializationMode": "Default",
      "ignoreProperties": [],
      "attributes": {
        "exclude": [
          "PBI_*"
        ]
      }
    }
  }
}
```

_When serializing a model, exclude all TMSL attributes starting with "PBI\_"._

Question is whether this would need to be more granular, i.e. are certain _PBI\_*_ attributes desirable in the payload? Is an additional `include` rule required to keep specific attributes?

**Comment by peterbud** [comment]
Mathias, this is exactly I was looking for!
For your question I believe having an include and exclude array with wildcards would work, and would provide a flexible solution.

Let's close the issue here, and track at #19

**Comment by mthierba** [comment]
@peterbud This feature is now live in the latest, [Beta.8](https://github.com/pbi-tools/pbi-tools/releases/tag/1.0.0-beta.8), release! Sorry this took a little longer. This ended up being a MASSIVE release - gonna take me a few days to write up all the changes and new features. Related to your request there is #61, the new `convert` action, which allows converting a PbixProj folder between different serialization formats, either in-place or into a new location.

What you can do is to add the new `annotations` setting into an existing `.pbixproj.json` (similar to https://github.com/pbi-tools/pbi-tools/blob/1.0.0-beta.8/data/Samples/Adventure%20Works%20DW%202020/.pbixproj.json), then run

    pbi-tools convert "{YOUR FOLDER}" -overwrite

Which will remove all those optional annotations, and will also ignore during subsequent extracts into the same location.

Check out all the options using the built-in cli docs:

    pbi-tools convert

**Comment by peterbud** [comment]
Many thanks @mthierba! I'll try this next week, and let you know the results.
